---
# Actualizar caché de los paquetes
- name: Actualizar caché de los repositorios
  yum:
    name: '*'
    state: latest
    update_cache: true
# Instalar MariaDB
- name: Instalación MariaDB
  yum:
          name:
            - mariadb-server
            - python3
            - python3-PyMySQL
            - firewalld
          state: latest

# Iniciar servicio MariaDB
- name: Iniciar servicio MariaDB
  service:
    name: mariadb
    enabled: true
    state: started
# Reiniciar el servicio de mariadb
- name: reiniciar servico MariaDB
  service:
    name: mariadb
    state: restarted
  tags: mariadb
      # Secure_installation y cambio de contraseña usuario root
- name: MySQL-secure_installation
  shell:
    echo -e "\nn\nY\nViewnext\nViewnext\nY\nn\nY\nY\n" | sudo mysql_secure_installation
  args:
    executable: /bin/bash
  tags: mariadb
# <--------------- IMPORTAR CONFIGURACIÓN A MARIADB CentOS ------------------------->

- name: Establecer configuración Mariadb CentOS
  template:
          src: /home/vagrant/src/recursos/50-server-centos.cnf
          dest: /etc/my.cnf.d/mariadb-server.cnf
          owner: root
          group: root
          mode: '0755'

- name: Reiniciar mariadb
  service:
          name: mariadb
          enabled: true
          state: restarted


# Creación de la base de datos de wordpress
- name: crear base de datos
  community.mysql.mysql_db:
    name: maria
    login_user: root
    login_password: Viewnext
    state: present
  tags: mariadb
# Usuario para la base de datos
- name: Crear usuario para base de datos de wordpress
  mysql_user:
    login_user: root
    login_password: Viewnext
    name: maria
    password: ccwp
    priv: 'maria.*:ALL,GRANT'
    host: '%'
    state: present
  tags: mariadb
# Habilitar MariaDb en Firewall
- name: Habilitar servicio mysql en firewall
  firewalld:
    service: mysql
    state: enabled
    permanent: yes
    immediate: yes
  tags: mariadb
# Abrir puerto 3306 en firewall para conexión remota
- name: abrir pueto 3306
  firewalld:
    port: 3306/tcp
    permanent: true
    state: enabled
  tags: mariadb
# Habilitar puerto 22 firewall
- name: Habilitar puerto 22
  firewalld:
    port: 22/tcp
    permanent: true
    state: enabled
# Reiniciar servicio firewall
- name: Reiniciar la configuración del firewall
  command: 
    cmd: firewall-cmd --reload
  tags: mariadb

#     <--------------- CREACIÓN DEL FICHERO BACKUP EN CASO DE QUE NO EXISTA -------------->

- name: Crear directorio backup
  become: true
  file:
          path: /backup
          state: directory

#       <----------- COPIA DEL ÚLTIMO BACKUP DEL CONTROL NODE AL SERVIDOR REMOTO ----------->

- name: Copiar backup a servidor remoto CentOS
  template:
          src: /home/vagrant/src/recursos/backup-file.sql
          dest: /backup/

#       <----------------------- RESTAURACIÓN DE LA BASE DE DATOS ---------------------->

- name: Restaurar base de datos
  mysql_db:
          login_user: root
          login_password: Viewnext
          name: maria
          state: import
          target: /backup/backup-file.sql
